### ISSUE TITLE
Unhandled exception whilst getting prices

### ISSUE THREAD

**Issue by nsaxelby** [nsaxelby/StockMarketPopupTicker#3]
![Screenshot](https://user-images.githubusercontent.com/20544595/63534091-39b2b700-c506-11e9-942a-5be7bd78029b.png)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Null object cannot be converted to a value type.
   at StockMarketPopupTickerApplication.Form1.GetStockPrices(ConfigSettingsObject settings)
   at StockMarketPopupTickerApplication.Form1.ShowStockPrices()
   at StockMarketPopupTickerApplication.Form1.showPricesNowMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by nsaxelby** [comment]
More details: IEX was responding with "   "changePercent":null," for one of my stocks ( FMC ). Seems to be only happening for a few stock symbols - and not consistently.
